requires 'Catalyst::Runtime' => '5.90050';
requires 'Catalyst::Plugin::ConfigLoader';
requires 'Catalyst::Plugin::Static::Simple';
requires 'Catalyst::Action::RenderView';
requires 'Moose';
requires 'namespace::autoclean';
requires 'Config::Any::Perl';
requires 'Catalyst::View::TT';
requires 'Catalyst::Plugin::StackTrace';
requires 'Catalyst::Plugin::Session';
requires 'Catalyst::Plugin::Session::Store::FastMmap';
requires 'Catalyst::Plugin::Session::State::Cookie';
requires 'CatalystX::SimpleLogin';
requires 'Catalyst::Plugin::Authentication';
requires 'Catalyst::Model::DBIC::Schema';
requires 'DBIx::Class';
requires 'HTML::FormHandler';
requires 'HTML::FormHandler::Model::DBIC';
requires 'Net::EPP';
requires 'Template';
requires 'Template::Plugin::JSON';
requires 'XML::LibXML';
requires 'XML::LibXML::Simple';
requires 'List::Util' => 1.55;
requires 'DBIx::Class::PassphraseColumn';
requires 'Authen::Passphrase::BlowfishCrypt';
requires 'Catalyst::Authentication::Store::DBIx::Class';
requires 'Catalyst::Plugin::Authorization::Roles';
requires 'String::Random';
requires 'LWP::UserAgent';
requires 'LWP::Protocol::https';
requires 'HTTP::Message';
requires 'Config::ZOMG';
requires 'Dir::Self';
requires 'Getopt::Long';
requires 'CatalystX::Resource' => '0.03';
requires 'DBIx::Class::InflateColumn::Serializer';
requires 'DBIx::Class::DeploymentHandler' => '0.002222';
requires 'DBIx::Class::Schema::Loader';
requires 'Data::Printer' => '1.000004';
requires 'JSON::PP';
requires 'Data::DPath';
requires 'Catalyst::Model::Adaptor';
requires 'DateTime::Format::Duration';
requires 'DateTime::Format::Strptime';
requires 'DateTime::Format::ISO8601';
requires 'DBIx::Class::TimeStamp';
requires 'DateTime::Format::Pg';
requires 'DBD::Pg';
requires 'HTTP::CookieJar';
requires 'URI';
requires 'Digest::MD5';
requires 'Package::Variant';
requires 'Path::Class' => 0.31;
requires 'MooseX::Types::Path::Class';
requires 'Child';
requires 'Term::ReadKey';
requires 'IO::Compress::Bzip2';
requires 'Catalyst::TraitFor::Model::DBIC::Schema::SchemaProxy';
requires 'Net::OpenSSH';
requires 'DBI';
requires 'MooseX::Types::Common::String';
requires 'Log::Any::Adapter::Dispatch';
requires 'Log::Dispatch::FileRotate';
requires 'IO::Interactive';
requires 'Pg::CLI';
requires 'Exporter';
requires 'FCGI';
requires 'FCGI::ProcManager';
requires 'Catalyst::Action::REST';
requires 'Catalyst::ControllerRole::CatchErrors';
requires 'Text::CSV';
requires 'Data::Compare';
requires 'HTML::Entities';
requires 'Text::Diff';
requires 'Regexp::Grammars';
requires 'Net::Whois::Raw';
requires 'IPC::Run3';
requires 'Template::Plugin::Unicode';
requires 'IO::File::WithPath';
requires 'Plack::Middleware::Assets';
requires 'Clone';
requires 'Selenium::Remote::Driver';
requires 'Parqus';

on 'test' => sub {
    requires 'Test::More' => '0.88';
    requires 'Test::Warnings';
    requires 'Test::WWW::Mechanize::Catalyst';
    requires 'Test::Fatal';
    requires 'Import::Into';
    requires 'DBD::Mock';
    requires 'File::Temp';
};
