version: '3.6'
services:
    db:
        image: postgres:15-alpine
        container_name: epplication-db
        environment:
            POSTGRES_USER: epplication
            POSTGRES_PASSWORD: epplication
            POSTGRES_DB: epplication
        volumes:
            - db_data:/var/lib/postgresql/data
    selenium:
        image: selenium/standalone-firefox:114.0-geckodriver-0.33-grid-4.10.0-20230614
        container_name: epplication-selenium
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "5900:5900"
    app:
        container_name: epplication-app
        image: davewood/epplication:latest
        depends_on:
            - db
        volumes:
            - app_data_job_exports:/home/epplication/EPPlication/root/job_exports
            - app_data_ssh_keys:/home/epplication/EPPlication/ssh_keys
        ports:
            - "8080:80"
volumes:
    db_data:
    app_data_job_exports:
    app_data_ssh_keys:
